---
# tasks file for ansible-preferences-server-data-loader

# These next tasks are an Ansible-paradigm version of https://github.com/gpii-ops/docker-preferences-server/blob/master/modify_preferences.sh

- name: copy test data to temporary directory (on control host) to use for templating
  synchronize:
    src: "{{ nodejs_app_install_dir }}/testData/preferences/"
    dest: /tmp/prefData/
    mode: pull

# We ignore the error here because a failure to list the directory results in an empty list for preferences_server_tmp_pref_data - the desired behaviour for the next step (do nothing if not priming)
- name: register the contents of the temporary directory (on control host) to use for templating
  shell: ls /tmp/prefData/*.json
  register: preferences_server_tmp_pref_data
  ignore_errors: true
  delegate_to: 127.0.0.1
  become: no

- name: create directory on remote host to hold modified data files
  file:
    dest: /tmp/prefData/
    state: directory

- name: template out modified test data to the remote host
  template:
    src: uploadedData.j2
    dest: "{{ item[1] }}"
  with_indexed_items: "{{ preferences_server_tmp_pref_data.stdout_lines }}"

- name: delete couchdb index if it exists
  uri:
    url: http://{{ preferences_server_data_loader_couchdb_host_address }}/preferences
    method: DELETE
    status_code: 200,404 # succeeds if it either deletes the index or returns that it can't be deleted due to not existing
  when: preferences_server_data_loader_clear_index

- name: create the couchdb index
  uri:
    url: http://{{ preferences_server_data_loader_couchdb_host_address }}/preferences
    method: PUT
    status_code: 201
  when: preferences_server_data_loader_clear_index

- name: install Kanso for interacting with couchdb
  npm:
    name: kanso
    state: present
    global: yes

- name: upload the modified test preferences files to couchdb
  shell: kanso upload {{ item }} http://{{ preferences_server_data_loader_couchdb_host_address }}/preferences
  with_fileglob: /tmp/prefData/*.json

- name: remove kanso
  npm:
    name: kanso
    state: absent
    global: yes
  when: preferences_server_data_loader_cleanup_after

- name: remove temp directory
  file:
    path: /tmp/prefData
    state: absent
  when: preferences_server_data_loader_cleanup_after
